import Footer from './Components/Footer'
import Front from './Components/Front'
import Header from './Components/Header'
import Page from './home/page'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Engineers Restaurant',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
                  
        {children}
        

        <Footer/>

      </body>
    </html>
  )
}
